{{- range $.Values.reconcilers }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .resource }}-cluster-role
rules:
  - apiGroups:
      - {{ .apiGroup }}
    resources:
      - {{ .resource }}
      - {{ .resource }}/status
      - {{ .resource }}/finalizers
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - create
      - delete
---
{{- end }}