= Quarkiverse Java Operator SDK
:extension-status: preview

This extension integrates the https://javaoperatorsdk.io[Java Operator SDK] project (JOSDK) with Quarkus, making it even easier to use both.

== Features

- Automatically generates a main class, so that the only thing that's required is to write a `ResourceController` implementation
- Automatically makes a Kubernetes/OpenShift client available for CDI injection
- Automatically setups an `Operator` instance, also available for CDI injection
- Automatically processes the controllers' configuration at build time, exposing all the available configuration of JOSDK via application properties
- Automatically registers controllers with the `Operator` and start them
- Automatically generates CRDs for all `CustomResource` implementations used by controllers
- Automatically generates Kubernetes descriptors (though support for this needs to be improved)
- Automatically generates CSV for all controllers (using the `quarkus-operator-sdk-csv-generator` extension) [Preview]
- Integrates with the Dev mode:
    * Watches your code for changes and reload automatically your operator if needed without having to hit an endpoint
    * Only re-generate the CRDs if a change impacting its generation is detected
    * Only re-process a controller's configuration if needed
    * Automatically apply the CRD to the cluster when it has changed
- Automatically generates CDI observers to allow for delayed registration of controllers (for example, to wait until some external resource is available)
- Supports micrometer registry extensions (adding a Quarkus-supported micrometer registry extension will automatically inject said registry into the operator)
- Automatically adds a SmallRye health check
- Can easily generate a Docker image via JIB
- Sets up reflection for native binary generation

== Installation

If you want to use this extension, you need to add the `quarkus-operator-sdk` extension first.
In your `pom.xml` file, add:

[source,xml]
----
<dependency>
    <groupId>io.quarkiverse.operatorsdk</groupId>
    <artifactId>quarkus-operator-sdk</artifactId>
</dependency>
----

If you want to use the CSV generator, you will first need to use Quarkus 2.3.0.Final and add the `quarkus-operator-sdk-csv-generator` extension first:

[source,xml]
----
<dependency>
    <groupId>io.quarkiverse.operatorsdk</groupId>
    <artifactId>quarkus-operator-sdk-csv-generator</artifactId>
</dependency>
----

[[extension-configuration-reference]]
== Extension Configuration Reference

include::config.adoc[leveloffset=+1,opts=optional]
