= Quarkiverse Java Operator SDK
:extension-status: preview

This extension integrates the https://javaoperatorsdk.io[Java Operator SDK] project (JOSDK) with Quarkus, making it even easier to use both.

== Features

- Automatically generates a main class, so that the only thing that's required is to write `Reconciler` implementation(s)
- Automatically makes a Kubernetes/OpenShift client available for CDI injection
- Automatically sets up an `Operator` instance, also available for CDI injection
- Automatically processes the reconcilers' configuration at build time, exposing all the available configuration of JOSDK via application properties
- Automatically registers reconcilers with the `Operator` and start them
- Automatically generates CRDs for all `CustomResource` implementations used by reconcilers
- Automatically generates Kubernetes descriptors
- Automatically generates the bundle manifests for all reconcilers (using the `quarkus-operator-sdk-bundle-generator` extension) [Preview]
- Integrates with the Dev mode:
* Watches your code for changes and reload automatically your operator if needed without having to hit an endpoint
* Only re-generates the CRDs if a change impacting its generation is detected
* Only re-processes a reconciler's configuration if needed
* Automatically apply the CRD to the cluster when it has changed
- Supports micrometer registry extensions (adding a Quarkus-supported micrometer registry extension will automatically inject said registry into the operator)
- Automatically adds a SmallRye health check
- Sets up reflection for native binary generation
- Customize the JSON serialization that the Fabric8 client relies on by providing an `ObjectMapperCustomizer` implementation, qualified with the `@KubernetesClientSerializationCustomizer` annotation

== Installation

If you want to use this extension, you need to add the `quarkus-operator-sdk` extension first.

You need to add minimally, the following to your `pom.xml` file:

[source,xml]
----
<dependency>
    <groupId>io.quarkiverse.operatorsdk</groupId>
    <artifactId>quarkus-operator-sdk</artifactId>
    <version>{extension version}</version>
</dependency>
----

However, it might be more convenient to use the `quarkus-operator-sdk-bom` dependency to ensure that all dependency versions are properly aligned:

[source,xml]
----
<dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.quarkiverse.operatorsdk</groupId>
        <artifactId>quarkus-operator-sdk-bom</artifactId>
        <version>{extension version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

      <!-- other dependencies as needed by your project -->

    </dependencies>
  </dependencyManagement>
----

If you do use the BOM, please do make sure to use the same Quarkus version as the one defined in the BOM when configuring the Quarkus plugin as the Quarkus Dev Mode will not work properly otherwise, failing with an error:

[source,shell]
----
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalStateException: Hot deployment of the application is not supported when updating the Quarkus version. The application needs to be stopped and dev mode started up again
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:138)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
----

If you want to use the Bundle generator, you will first need to use Quarkus 2.3.0.Final or above and add the `quarkus-operator-sdk-bundle-generator` extension first:

[source,xml]
----
<dependency>
    <groupId>io.quarkiverse.operatorsdk</groupId>
    <artifactId>quarkus-operator-sdk-bundle-generator</artifactId>
    <version>{extension version}</version>
</dependency>
----

== Deployment

This section explains how to deploy your operator using the https://olm.operatorframework.io/[Operator Lifecycle Manager (OLM)] by following the next steps:

0. Requirements

Make sure you have installed the https://github.com/operator-framework/operator-registry[opm] command tool and are connected to a Kubernetes cluster on which OLM is installed.

1. Generate the Operator image and bundle manifests

Quarkus provides https://quarkus.io/guides/container-image[several extensions] to build the container image.
For example, the https://github.com/quarkiverse/quarkus-operator-sdk/tree/main/samples/joke#deployment[Joke] sample uses the https://quarkus.io/guides/container-image#jib[Quarkus Jib container image extension] to build the image.
So, you first need to configure one of these extensions as you prefer.
Then, you need to add the `quarkus-operator-sdk-bundle-generator` extension:

[source,xml]
----
<dependency>
    <groupId>io.quarkiverse.operatorsdk</groupId>
    <artifactId>quarkus-operator-sdk-bundle-generator</artifactId>
</dependency>
----

This extension generates the Operator bundle manifests in the `target/bundle` directory.

Finally, to generate the operator image and the bundle manifests at once, you simply need to run the next Maven command:

[source,shell script]
----
mvn clean package -Dquarkus.container-image.build=true \
    -Dquarkus.container-image.push=true \
    -Dquarkus.container-image.registry=<your container registry. Example: quay.io> \
    -Dquarkus.container-image.group=<your container registry namespace> \
    -Dquarkus.kubernetes.namespace=<the kubernetes namespace where you will deploy the operator> \
    -Dquarkus.operator-sdk.bundle.package-name=<the name of the package that bundle image belongs to> \
    -Dquarkus.operator-sdk.bundle.channels=<the list of channels that bundle image belongs to>
----

For example, if we want to name the package `my-operator` and use the `alpha` channels, we would need to append the properties `-Dquarkus.operator-sdk.bundle.package-name=my-operator -Dquarkus.operator-sdk.bundle.channels=alpha`.

[NOTE]
====
Find more information about channels and packages https://olm.operatorframework.io/docs/best-practices/channel-naming/#channels[here].
====

[NOTE]
====
If you're using an insecure container registry, you'll also need to append the next property to the Maven command `-Dquarkus.container-image.insecure=true`.
====

2. Build the Operator Bundle image

An Operator Bundle is a container image that stores Kubernetes manifests and metadata associated with an operator.
You can find more information about this https://olm.operatorframework.io/docs/tasks/creating-operator-bundle/[here].
In the previous step, we generated the bundle manifests at `target/bundle` which includes a ready-to-use `target/bundle/bundle.Dockerfile` Dockerfile that you will use to build and push the final Operator Bundle image to your container registry:

[source,shell script]
----
MY_BUNDLE_IMAGE=<your container registry>/<your container registry namespace>/<bundle image name>:<tag>
docker build -t $MY_BUNDLE_IMAGE -f target/bundle/bundle.Dockerfile target/bundle
docker push $MY_BUNDLE_IMAGE
----

For example, if we want to name our bundle image as `my-manifest-bundle`, our container registry is `quay.io`, our Quay user is `myuser` and the tag we're releasing is `1.0`, the final `MY_BUNDLE_IMAGE` property would be `quay.io/myuser/my-manifest-bundle:1.0`.

3. Make your operator available within a Catalog

OLM uses catalogs to discover and install Operators and their dependencies.
So, a catalog is similar to a repository of operators and their associated versions that can be installed on a cluster.
Moreover, the catalog is also a container image that contains a collection of bundles and channels.
Therefore, we'd need to create a new catalog (or update an existing one if you're already have one), build/push the catalog image and then install it on our cluster.

So far, we have already built the Operator bundle image at `$MY_BUNDLE_IMAGE` (see above) and next, we need to add this Operator bundle image into our catalog.
For doing this, we'll use the `olm` tool as follows:

[source,shell script]
----
CATALOG_IMAGE=<catalog container registry>/<catalog container registry namespace>/<catalog name>:<tag>
opm index add \
    --bundles $MY_BUNDLE_IMAGE \
    --tag $CATALOG_IMAGE \
    --build-tool docker
docker push $CATALOG_IMAGE
----

For example, if our catalog name is `my-catalog`, our container registry for the catalog is `quay.io`, our Quay user is `myuser` and the container tag we're releasing is `59.0`, the final `CATALOG_IMAGE` property would be `quay.io/myuser/my-catalog:59.0`.

[NOTE]
====
If you're using an insecure registry, you'd need to append the argument `--skip-tls` to the `opm index` command.
====

Once we have our catalog image built and pushed at `$CATALOG_IMAGE`, we need to install it in the same namespace where OLM is running (by default, OLM is running in the `operators` namespace, we will use the `OLM_NAMESPACE` property to represent this namespace) on our cluster using the `CatalogSource` resource by doing the next command:

[source,shell script]
----
cat <<EOF | kubectl apply -f -
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: my-catalog-source
  namespace: $OLM_NAMESPACE
spec:
  sourceType: grpc
  image: $CATALOG_IMAGE
EOF
----

Once the catalog is installed, you should see the catalog pod up and running:

[source,shell script]
----
kubectl get pods -n $OLM_NAMESPACE --selector=olm.catalogSource=my-catalog-source
----

4. Install your operator via OLM

OLM deploys operators via https://olm.operatorframework.io/docs/tasks/install-operator-with-olm/#install-your-operator[subscriptions].
Creating a  `Subscription` will trigger the operator deployment.
You can simply create the `Subscription` resource that contains the operator name and channel to install by running the following command:

[source,shell script]
----
cat <<EOF | kubectl create -f -
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-subscription
  namespace: <Kubernetes namespace where your operator will be installed>
spec:
  channel: alpha
  name: my-operator-name
  source: my-catalog-source
  sourceNamespace: $OLM_NAMESPACE
EOF
----

[NOTE]
====
We'll install the operator in the target namespace defined in the metadata object.
The `sourceNamespace` value is the Kubernetes namespace where the catalog was installed on.
====

Once the subscription is created, you should see your operator pod up and running:

[source,shell script]
----
kubectl get csv -n $OLM_NAMESPACE my-operator-name
----

[[extension-configuration-reference]]
== Extension Configuration Reference

include::config.adoc[leveloffset=+1,opts=optional]
