quarkus.kubernetes-client.devservices.override-kubeconfig=true
quarkus.operator-sdk.crd.validate=false
quarkus.operator-sdk.use-v1-metrics=true
## randomize Quarkus port for tests
quarkus.http.test-port=0
