apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: externals.halkyon.io
spec:
  conversion:
    strategy: None
  group: halkyon.io
  names:
    kind: External
    listKind: ExternalList
    plural: externals
    singular: external
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              type: object
            status:
              type: object
          type: object
      served: true
      storage: true