apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jokerequestreconciler-role-binding
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: jokerequestreconciler-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ .Chart.Name }}