apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: quarkus
    app.kubernetes.io/name: quarkus-operator-sdk-samples-joke
    app.kubernetes.io/version: 6.2.2-SNAPSHOT
  name: quarkus-operator-sdk-samples-joke