name: Release snapshot of next-fabric8-version branch each day at midnight

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-for-latest-quarkus-version:
    uses: ./.github/workflows/build-for-quarkus-version.yml
    with:
      quarkus-pr: "42335"
      java-version: 21
      native-modules: "integration-tests,samples"
      profiles: "use-snapshots,override-fkc"
      mvnArgs: "-Dfkc.version=7.0-SNAPSHOT -Ddefault=false"
      branch: "main"