name: Quarkiverse Perform Release
run-name: Perform ${{github.event.inputs.tag || github.ref_name}} Release
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: 'Tag to release'
        required: true
      ref:
        description: 'Branch or tag to deploy'
        type: string
        required: false
      dry_run:
        description: 'Dry run the release'
        required: false
        type: boolean
        default: false

permissions:
  attestations: write
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  perform-release:
    name: Perform Release
    uses: quarkiverse/.github/.github/workflows/perform-release.yml@main
    secrets: inherit
    with:
      version: ${{github.event.inputs.tag || github.ref_name}}

  update-quarkus-platform:
    needs:
      - perform-release
    uses: ./.github/workflows/release-update-quarkus-platform.yml
    with:
      tag: ${{github.event.inputs.tag || github.ref_name}}
    secrets:
      qosdk-bot-token: ${{ secrets.QOSDK_BOT_TOKEN }}
