name: Open quarkus-platform PR

on:
  workflow_call:
    inputs:
      qosdk-version:
        type: string
        required: true
      quarkus-platform-branches:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      qosdk-version:
        type: string
        required: true
        description: 'Which QOSDK version to release'
      quarkus-platform-branches:
        type: string
        required: true
        description: 'Which Quarkus platform branches to target in the form: main,3.32,3.27'
jobs:
  setup:
    runs-on: ubuntu-slim
    outputs:
      quarkus-platform-branches: ${{ steps.transform-input.outputs.quarkus-platform-branches }}
    steps:
      - name: Configure Quarkus platform branches array
        id: transform-input
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            branches=$(jq 'split(",")' -Rc <(echo '${{ inputs.quarkus-platform-branches }}'))
          else
            branches="${{inputs.quarkus-platform-branches}}"
          fi
          echo "${branches}"
          echo "quarkus-platform-branches=${branches}" >> $GITHUB_OUTPUT

  quarkus-platform-pr:
    runs-on: ubuntu-slim
    needs: setup
    continue-on-error: true
    strategy:
      matrix:
        quarkus-platform-branch: ${{ fromJson(needs.setup.outputs.quarkus-platform-branches) }}
    steps:
      - uses: actions/checkout@v6
        with:
          repository: quarkusio/quarkus-platform
          ref: ${{matrix.quarkus-platform-branch}}

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: Update QOSDK version to ${{inputs.qosdk-version}} in quarkus-platform ${{matrix.quarkus-platform-branch}}
        run: |
          ./mvnw -B versions:set-property -Dproperty=quarkus-operator-sdk.version -DnewVersion=${{inputs.qosdk-version}}
          ./mvnw -Dsync

      - name: Create quarkus-platform pull request
        uses: peter-evans/create-pull-request@v8
        id: qp-pr
        with:
          title: "Update QOSDK to ${{inputs.qosdk-version}} for ${{matrix.quarkus-platform-branch}}"
          commit-message: "Update QOSDK to ${{inputs.qosdk-version}}"
          committer: metacosm <metacosm@users.noreply.github.com>
          author: metacosm <metacosm@users.noreply.github.com>
          branch: qosdk-release-${{inputs.qosdk-version}}-${{matrix.quarkus-platform-branch}}
          token: ${{ secrets.QOSDK_BOT_TOKEN }}
          push-to-fork: qosdk-bot/quarkus-platform
          delete-branch: true

      - name: Check quarkus-platform PR
        if: ${{ steps.qp-pr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.qp-pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.qp-pr.outputs.pull-request-url }}"
