name: Open quarkus-platform PR

on:
  workflow_call:
    inputs:
      qosdk-version:
        type: string
        required: true
      quarkus-platform-branch:
        type: string
        required: false
        default: 'main'
    secrets:
      qosdk-bot-token:
        required: true

jobs:
  quarkus-platform-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: quarkusio/quarkus-platform
          ref: ${{inputs.quarkus-platform-branch}}

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: Update QOSDK version to ${{inputs.qosdk-version}} in quarkus-platform ${{inputs.quarkus-platform-branch}}
        run: |
          ./mvnw -B versions:set-property -Dproperty=quarkus-operator-sdk.version -DnewVersion=${{inputs.qosdk-version}}
          ./mvnw -Dsync

      - name: Create quarkus-platform pull request
        uses: peter-evans/create-pull-request@v6
        id: qp-pr
        with:
          title: "Update QOSDK to ${{inputs.qosdk-version}} for ${{inputs.quarkus-platform-branch}}"
          commit-message: "Update QOSDK to ${{inputs.qosdk-version}}"
          committer: metacosm <metacosm@users.noreply.github.com>
          author: metacosm <metacosm@users.noreply.github.com>
          branch: qosdk-release-${{inputs.qosdk-version}}-${{inputs.quarkus-platform-branch}}
          token: ${{ secrets.qosdk-bot-token }}
          push-to-fork: qosdk-bot/quarkus-platform
          delete-branch: true

      - name: Check quarkus-platform PR
        if: ${{ steps.qp-pr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.qp-pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.qp-pr.outputs.pull-request-url }}"