name: Release snapshots of selected branches on push

on:
  push:
    branches: [ main, next, next-fabric8-version ]

defaults:
  run:
    shell: bash

permissions:
  attestations: write
  id-token: write
  contents: read

jobs:
  release-snapshot:
    uses: ./.github/workflows/release-snapshot.yml
    secrets: inherit
    with:
      branch: "${{github.ref}}"
